9 lesson
abr2001/qna5 pull request #10
Opened 2017-04-07 18:05 UTC by abr2001

2017-04-08 08:57 UTC, vkurennov requested changes

2017-04-08 08:57 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +        format.json { render json: {rating: @ratable.rating, rate: current_user.rate_of(@ratable), id: @ratable.id } }
Если у тебя только json поддерживается, то нет смысла в блоке `respond_to`

2017-04-08 08:57 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +    unless current_user.already_has_rate_of?(@ratable)
Какое-то длинное название метода. Лучше покорочен, например, `has_rate?`

2017-04-08 08:57 UTC, vkurennov commented on app/models/concerns/associations.rb
> +module Associations
Это неправильный консерн. Суть консерна в объединении логически связанного кода. А как связаны аттачменты и голоса? никак. То есть это должны быть  разные консерны.

2017-04-08 08:57 UTC, vkurennov commented on app/models/concerns/has_user.rb
> +    validates  :user, presence: true
Это лишнее, т.к. в 5-х рельсах ассоциации `belongs_to` и так валидруются по-умолчанию

2017-04-08 08:57 UTC, vkurennov commented on app/models/rate.rb
> +    if Rate.where(user_id: user_id).
Во-первых, в одном where можно указать несколько условий, во-вторых, на то в рельсах и есть полиморфные ассоциации, чтобы не указывать отдельно  id и тип. То есть достаточно указывать ratable и объект

2017-04-08 08:57 UTC, vkurennov commented on app/models/rate.rb
> +  before_validation :check_user_already_has_rate
Почему это коллбек, а не кастомная валидация (`validate`)?

2017-04-08 08:57 UTC, vkurennov commented on app/views/questions/_question.html.haml
> +    - if user_signed_in? && !current_user.author_of?(@question)
Блок голосования за вопрос и ответ можно сделать универсальным и вынести в паршл, для этого понадобится сделать классы элементов не привязанные к вопросу/ответу и использовать [polymorphic_path](http://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html)

2017-04-08 08:57 UTC, vkurennov commented on config/routes.rb
> +      get :rate
get-запросы не должны менять состояние системы

2017-04-08 08:57 UTC, vkurennov commented on config/routes.rb
>        get :set_best
И опять тут get, хотя должен быть как минимуи post, видимо, я это пропустил.

2017-04-08 08:57 UTC, vkurennov commented on r.txt
> +                     Prefix Verb   URI Pattern                                                   Controller#Action
Это что?

2017-04-08 08:57 UTC, vkurennov commented on spec/features/answers/rate_spec.rb
> +    within('.answer') do
Это отдельный сценарий.

2017-04-08 08:57 UTC, vkurennov commented on spec/features/answers/rate_spec.rb
> +    within('.answer') do
Голосование против - тоже отдельный сценарий

2017-04-09 07:52 UTC, abr2001 commented on app/models/rate.rb
> +  before_validation :check_user_already_has_rate
не помню уже, зачем так сделал )

2017-04-09 07:55 UTC, abr2001 commented on app/models/rate.rb
> +    if Rate.where(user_id: user_id).
дурацкая прbвычка дробить where, про ratable не знал, круто!!!

2017-04-09 08:13 UTC, abr2001 commented on config/routes.rb
>        get :set_best
изменил на patch

2017-04-09 08:14 UTC, abr2001 commented on r.txt
> +                     Prefix Verb   URI Pattern                                                   Controller#Action
это роуты нечаянно закоммитил

2017-04-09 08:14 UTC, abr2001 commented on r.txt
> +                     Prefix Verb   URI Pattern                                                   Controller#Action
))

2017-04-17 06:05 UTC, merged