10 lesson
abr2001/qna5 pull request #11
Opened 2017-11-11 15:18 UTC by abr2001

2017-11-12 09:37 UTC, vkurennov requested changes

2017-11-12 09:37 UTC, vkurennov commented on app/channels/comments_channel.rb
> +    stream_from "comments"
Для комментариев тоже нужно учитывать id вопроса, иначе у тебя в одном стриме будут идти вообще все комментарии в системе, что будет создавать лишнюю нагрузку на браузер, когда он будет фильтровать нужные комментарии. Т.е. тут схема та же, что и с ответами

2017-11-12 09:37 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
Не нужно делать комментарии консерном. Это отдельный, самотстоятельный ресурс, поэтому его нужно сделать отдельным контроллером.

2017-11-13 10:08 UTC, palkan-th requested changes
А где тесты на сокеты? Хотя бы системны, через Capybara.

Но лучше и функциональные, и юниты (см. https://github.com/palkan/action-cable-testing)

2017-11-13 10:08 UTC, palkan-th commented on app/assets/javascripts/answers.coffee
> +    return if gon.user_id == data['user_id']
А если у пользователя открыто две вкладки? Получается, он не увидит в одной из них нового ответа. То же самое касается и комментариев.

Нужно проверять наличие ответа на странице (как DOM элемента).
При этом нужно это делать и в обработке AJAX ответа на создание, так как мы не знаем, что будет раньше – ответ на AJAX запрос или получение сообщения в сокете.

2017-11-13 10:08 UTC, palkan-th commented on app/assets/javascripts/templates/answer.jst.skim
> +          = @body
А кнопки на удаление/редактирование для автора?

2017-11-13 10:08 UTC, palkan-th commented on app/controllers/comments_controller.rb
> +            comment: JSON.parse(@comment.to_json),
Что это за трюк? Может, `@comment.as_json`?

А вообще, достаточно просто `@comment`, в итоге будет вызван `to_json`

2017-11-13 14:17 UTC, abr2001 commented on app/controllers/comments_controller.rb
> +            comment: JSON.parse(@comment.to_json),
исправил

2017-11-14 17:10 UTC, merged