7 lesson
abr2001/qna5 pull request #8
Opened 2017-03-14 17:41 UTC by abr2001

2017-03-15 11:10 UTC, vkurennov requested changes

2017-03-15 11:10 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      Answer.where(question_id: @answer.question).where(best: true).update_all(best: false)
1. Т.к. идет несколько апдейтов, это надо обернуть в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)
2. Это бизнес-логика, ей место в модели. А здесь просто вызывай метод модели

2017-03-15 11:10 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author_of?(@question)
А если это не автор? Все равно рендерим вьюху и все апдейтим? Лучше возвращать 403 статус для этого

2017-03-15 11:10 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer)
А если это не автор? Все равно рендерим вьюху и все апдейтим? Лучше возвращать 403 статус для этого

2017-03-15 11:10 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer.question)
Если условие не выполняется, надо вернуть 403 статус

2017-03-15 11:10 UTC, vkurennov commented on app/models/answer.rb
> +    if best != best_was and Answer.where(best: true).where(question_id: question_id).count > 0
Не использй and, используй &&
И можно гораздо проще сделать валидацию: `question.answers.where(best: true).exists?`

2017-03-15 11:10 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +  $('#answer-<%= @answer.id %>').html("");
Используй `remove`

2017-03-15 14:28 UTC, abr2001 commented on app/controllers/answers_controller.rb
> +      Answer.where(question_id: @answer.question).where(best: true).update_all(best: false)
тогда уже наверное в Service лучше вынести, зачем модель логикой грузить?

2017-03-15 18:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      Answer.where(question_id: @answer.question).where(best: true).update_all(best: false)
А зачем плодить классы без надобности?

2017-03-15 18:33 UTC, vkurennov requested changes

2017-03-15 18:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render status: :forbidden
Используй `head :forbidden`, это то же самое, но более правильно с т.з. http-протокола

2017-03-15 18:33 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'Must be the best only one answer' do
Это тест на валидацию, а где тесты на сам метод, который меняет состояние ответа?

2017-03-17 18:57 UTC, vkurennov approved these changes

2017-03-17 18:57 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'Set_best must change attributes best in database' do
Вообще, в юнит-тестах принято правило "один тест - один expect", поэтому этот тест надо разбить на 3.

2017-03-17 18:57 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.best).to eq(true)
`expect(answer).to be_best`

2017-03-20 03:52 UTC, merged